# Generated by Django 4.2.1 on 2023-05-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teashop', '0002_person_product_delete_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
